package com.hatchlab.securityevent;

public enum SecurityEventType {
    LOGIN_ATTEMPT,
    LOGIN_FAILURE,
    LOGIN_SUCCESS,
    RATE_LIMIT_TRIGGERED,
    CLIENT_THROTTLED,
    ACCOUNT_LOCKED,
    SUSPICIOUS_ACTIVITY,
    AUTHENTICATION_BLOCKED,
    SIMULATION_STARTED,
    SIMULATION_STOPPED,
    SIMULATION_COMPLETED
}